### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by iMerica** [fhussonnois/docker-storm#4] opened 2015-04-29 20:12 UTC
Hi, thanks for putting this together! When running the start options you provided for Docker Compose, I'm seeing this in Storm UI:

```
org.apache.thrift7.transport.TTransportException: java.net.NoRouteToHostException: No route to host
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:183)
	at org.apache.thrift7.transport.TFramedTransport.open(TFramedTransport.java:81)
	at backtype.storm.thrift$nimbus_client_and_conn.invoke(thrift.clj:75)
	at backtype.storm.ui.core$cluster_configuration.invoke(core.clj:472)
	at backtype.storm.ui.core$fn__8260.invoke(core.clj:844)
	at compojure.core$make_route$fn__6447.invoke(core.clj:93)
	at compojure.core$if_route$fn__6435.invoke(core.clj:39)
	at compojure.core$if_method$fn__6428.invoke(core.clj:24)
	at compojure.core$routing$fn__6453.invoke(core.clj:106)
	at clojure.core$some.invoke(core.clj:2443)
	at compojure.core$routing.doInvoke(core.clj:106)
	at clojure.lang.RestFn.applyTo(RestFn.java:139)
	at clojure.core$apply.invoke(core.clj:619)
	at compojure.core$routes$fn__6457.invoke(core.clj:111)
	at ring.middleware.reload$wrap_reload$fn__6482.invoke(reload.clj:14)
	at backtype.storm.ui.core$catch_errors$fn__8307.invoke(core.clj:909)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__7124.invoke(keyword_params.clj:27)
	at ring.middleware.nested_params$wrap_nested_params$fn__7163.invoke(nested_params.clj:65)
	at ring.middleware.params$wrap_params$fn__7096.invoke(params.clj:55)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__7191.invoke(multipart_params.clj:103)
	at ring.middleware.flash$wrap_flash$fn__7372.invoke(flash.clj:14)
	at ring.middleware.session$wrap_session$fn__7361.invoke(session.clj:43)
	at ring.middleware.cookies$wrap_cookies$fn__7292.invoke(cookies.clj:160)
	at ring.adapter.jetty$proxy_handler$fn__7572.invoke(jetty.clj:16)
	at ring.adapter.jetty.proxy$org.mortbay.jetty.handler.AbstractHandler$0.handle(Unknown Source)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:928)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.net.NoRouteToHostException: No route to host
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift7.transport.TSocket.open(TSocket.java:178)
	... 33 more
```

**Comment by fhussonnois** [comment] 2015-05-08 13:00
Hi,

You may try to run each container as follows : 

$ docker-compose -p storm -f ./docker-storm.yml up nimbus
$ docker-compose -p storm -f ./docker-storm.yml up --no-deps supervisor
$ docker-compose -p storm -f ./docker-storm.yml up --no-deps ui

**Comment by treper** [comment] 2015-08-17 11:08
I have the same problem. How did you solve it ?

**Comment by flaugh** [comment] 2015-10-22 06:27
@fhussonnois 
Thanks, it works!
But what's the root cause?

**Comment by fhussonnois** [comment] 2015-10-22 13:26
Hi,

I don't know - maybe some states are correputed due to containers are restart by docker-compose.
Try to rm your containers before restarting them with docker-compose.

BTW : docker-compose sould not be used in production.

Thank you. I close this issue.

**Closed by fhussonnois** 2015-10-22 13:26 UTC
